import { useState } from "react";
import { Plus, Trash2, StickyNote, ArrowLeft } from "lucide-react";
import { useNotes, useCreateNote, useDeleteNote } from "@/hooks/use-notes";
import { motion, AnimatePresence } from "framer-motion";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"; // Ensure these exist or use Radix primitives

// Minimal Dialog Implementation since ui/dialog might not be fully generated by me here
// In a real scenario, I'd generate the full UI library. 
// For now, I'll build a custom modal to ensure it works perfectly.

function CreateNoteModal({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const createNote = useCreateNote();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title || !content) return;
    
    await createNote.mutateAsync({ title, content, category: "General" });
    setTitle("");
    setContent("");
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-card w-full max-w-md rounded-2xl border border-border p-6 shadow-2xl"
      >
        <h2 className="text-xl font-bold mb-4">New Note</h2>
        <form onSubmit={handleSubmit} className="space-y-4">
          <input
            placeholder="Title"
            value={title}
            onChange={e => setTitle(e.target.value)}
            className="w-full bg-background border border-border rounded-xl px-4 py-2 focus:ring-2 focus:ring-primary/20 outline-none"
          />
          <textarea
            placeholder="Content..."
            rows={4}
            value={content}
            onChange={e => setContent(e.target.value)}
            className="w-full bg-background border border-border rounded-xl px-4 py-2 focus:ring-2 focus:ring-primary/20 outline-none resize-none"
          />
          <div className="flex gap-3 justify-end">
            <button type="button" onClick={onClose} className="px-4 py-2 text-muted-foreground hover:text-foreground">Cancel</button>
            <button 
              type="submit" 
              disabled={createNote.isPending}
              className="bg-primary text-primary-foreground px-6 py-2 rounded-xl font-medium hover:bg-primary/90 disabled:opacity-50"
            >
              {createNote.isPending ? "Saving..." : "Save Note"}
            </button>
          </div>
        </form>
      </motion.div>
    </div>
  );
}

export default function Notes() {
  const { data: notes, isLoading } = useNotes();
  const deleteNote = useDeleteNote();
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <div className="p-6 max-w-5xl mx-auto h-full flex flex-col">
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-3">
          <button onClick={() => window.history.back()} className="p-2 hover:bg-muted rounded-lg transition-colors" data-testid="button-back">
            <ArrowLeft className="w-5 h-5 text-muted-foreground" />
          </button>
          <div>
            <h1 className="text-3xl font-bold font-display">Notes</h1>
            <p className="text-muted-foreground mt-1">Save your calculations and ideas</p>
          </div>
        </div>
        <button 
          onClick={() => setIsModalOpen(true)}
          className="bg-primary hover:bg-primary/90 text-primary-foreground px-4 py-2 rounded-xl flex items-center gap-2 font-medium transition-colors shadow-lg shadow-blue-500/20"
        >
          <Plus className="w-5 h-5" />
          New Note
        </button>
      </div>

      <CreateNoteModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} />

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1,2,3].map(i => <div key={i} className="h-40 bg-card/50 rounded-2xl animate-pulse" />)}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 pb-20">
          <AnimatePresence>
            {notes?.map((note) => (
              <motion.div
                key={note.id}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                className="group bg-card hover:bg-card/80 border border-border/50 rounded-2xl p-5 transition-all hover:shadow-lg relative"
              >
                <div className="flex justify-between items-start mb-2">
                  <div className="w-8 h-8 rounded-lg bg-yellow-500/10 flex items-center justify-center mb-2">
                    <StickyNote className="w-4 h-4 text-yellow-500" />
                  </div>
                  <button 
                    onClick={() => deleteNote.mutate(note.id)}
                    className="opacity-0 group-hover:opacity-100 p-2 text-destructive hover:bg-destructive/10 rounded-lg transition-all"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
                <h3 className="font-bold text-lg mb-2">{note.title}</h3>
                <p className="text-muted-foreground text-sm line-clamp-3">{note.content}</p>
                <div className="mt-4 text-xs text-muted-foreground/50">
                  {new Date(note.createdAt!).toLocaleDateString()}
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
          
          {notes?.length === 0 && (
            <div className="col-span-full flex flex-col items-center justify-center py-20 text-muted-foreground opacity-50">
              <StickyNote className="w-16 h-16 mb-4" />
              <p>No notes yet. Create one to get started!</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
